### ISSUE TITLE
duplicate transaction

### ISSUE THREAD

**Issue by tianyalangzi** [eocschain/eocs#2]
3040008 tx_duplicate: Duplicate transaction
duplicate transaction cc7804d8477c21a609302fff798512d6c81c22e57df5b1374c99336ab01c7395
    {"id":"cc7804d8477c21a609302fff798512d6c81c22e57df5b1374c99336ab01c7395"}
    thread-0  producer_plugin.cpp:388 on_incoming_transaction_async

**Comment by tianyalangzi** [comment]
Duplicate transaction occurred when I used eoc_relay_plugin mode.

**Comment by secondtonone1** [comment]
I have solved the problem.
The problem is that duplicate slot functions are bound.
Typically, the eoc_plugin simply binds to a single invocation
