### ISSUE TITLE
full node coredump

### ISSUE THREAD

**Issue by tianyalangzi** [eocschain/eocs#24]
A 全节点（db_read_mode::SPECULATIVE） ,B 出块节点
 a1 交易发送至A执行成功，但B出块节点执行a1交易失败报错（3050003），a1交易被A放入unapplied_transactions 结构，接着 A节点的a1交易会进入如下代码代码流程（主要两点）： 
https://github.com/eocschain/eocs/blob/25a50e3258f97211976632d0a7544ebde3f7232c/libraries/chain/controller.cpp#L1105. 
https://github.com/eocschain/eocs/blob/25a50e3258f97211976632d0a7544ebde3f7232c/plugins/producer_plugin/producer_plugin.cpp#L1260.    
多次删除同一数据导致A node coredump ！ 
主要原因分析：  
 https://github.com/eocschain/eocs/blob/25a50e3258f97211976632d0a7544ebde3f7232c/libraries/chain/controller.cpp#L1104   该异常非该函数能识别异常，导致contronller内执行erase操作，同样错误 producer插件无法识别而同时执行了erase操作导致node coredump。
<img width="1435" alt="node_core" src="https://user-images.githubusercontent.com/10104985/55485619-5f294c00-565d-11e9-810b-d3e7decbaa8e.png">.

**Comment by secondtonone1** [comment]
fix full node coredump problems by below code:

void relay::on_applied_transaction(const transaction_trace_ptr& t) {
   if(t->except){
      ilog("on_applied_transaction failed");
      return;
   }
//...
}
