### ISSUE TITLE
Icp packet cannot be sent

### ISSUE THREAD

**Issue by tianyalangzi** [eocschain/eocs#4]
------------tx log----------  
warn  2019-01-12T08:23:10.003 thread-0  transaction.cpp:115           operator()           ] actions: ["dummy"]
executed transaction: d99c450d21660c7929d7f6202ffeebc40909f629e45d961479656c23df823eda  104 bytes  509 us
warn  2019-01-12T08:23:10.003 thread-0  transaction.cpp:75            print_result         ] ^Mwarning: transaction executed locally, but may not be confirmed by the network yet
warn  2019-01-12T08:23:10.011 thread-0  transaction.cpp:115           operator()           ] actions: ["addblocks"]
executed transaction: 9c33ff5dc845ab94e5eb63fe14ccbd2db00c19109b0732d572e7a21085c58c8a  1896 bytes  7132 us
     
-------icp_relay--on_irreversible_block log----------  
info  2019-01-12T08:23:11.501 thread-0  chain_plugin.cpp:678          operator()           ] ======== irreversible_block_channel======
info  2019-01-12T08:23:11.504 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 27acdf4f1f106ca9... #1270 @ 2019-01-12T08:23:11.500 signed by eosio [trxs: 0, lib: 1269, conf: 0, latency: 4 ms]
info  2019-01-12T08:23:11.505 thread-0  icp_relay.cpp:405             on_irreversible_bloc ] on_irreversible_block block 1268,0
info  2019-01-12T08:23:11.505 thread-0  icp_relay.cpp:422             on_irreversible_bloc ] on_irreversible_block tx.empty,0.   
    
----------------------------------      
When the icp plugin is started by a sync node, the s->trxs of on_irreversible_block is empty，so icp packet cannot be sent!
https://github.com/eocschain/eocs/blob/03773e962b7428235fdadbd1dd14461459deaaa2/plugins/icp_relay_plugin/icp_relay.cpp#L405  
https://github.com/eocschain/eocs/blob/03773e962b7428235fdadbd1dd14461459deaaa2/plugins/eoc_relay_plugin/icp_relay.cpp#L762

**Comment by ridewindx** [comment]
Fixed.

Fullnode receives block_state with empty field `vector<transaction_metadata_ptr> trxs`. So do not rely on it.
