### ISSUE TITLE
global_sequence inconsistencies

### ISSUE THREAD

**Issue by tianyalangzi** [eocschain/eocs#9]
full node  
 info  2019-01-23T06:37:14.029 thread-0  controller.cpp:981            print_action_receipt ] action_receipt data is act_digest is 981:dbd50f13e27da734382520a6b7258824b8262d0d8797425d1ce1219c3c8d5fcc receiver is eocseosioicp global_sequence is 1611 recv_sequence is39 code_sequence is1 abi_sequence is1. 
produce node.  
info  2019-01-23T06:37:14.018 thread-0  controller.cpp:981            print_action_receipt ] action_receipt data is act_digest is 981:3ac342d17ac74cc140fe762e85cc801b524d425c4c90328963cb752a6c0ee256 receiver is eosio global_sequence is 1611 recv_sequence is1411 code_sequence is2 abi_sequence is2. 
Global_sequence should be based on produce node！  
https://github.com/eocschain/eocs/blob/5f0c2941b887e25b1a7e9b77b45394b9c4c9fb41/plugins/icp_relay_plugin/icp_relay.cpp#L249

**Comment by secondtonone1** [comment]
Comment the code below
if (send_transactions_.find(t->id) != send_transactions_.end()) return; // has been handled
